# Nixpacks configuration for Railway deployment
# This configures how Railway builds and serves the JDM Portal Node.js application

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --production"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"